name: toktok
description: A TikTok-like app with a gem mine theme.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  # Temporarily commenting out heavy dependencies
  # rive: ^0.12.4
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6
  # firebase_storage: ^11.5.6
  # just_audio: ^0.9.36
  camera: ^0.10.5+9
  video_player: ^2.8.2
  permission_handler: ^11.3.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700 